### ISSUE TITLE
Changing servlet context path does not work anymore

### ISSUE THREAD

**Issue by gregor-rieble** [gessnerfl/fake-smtp-server#147]
Before 2.0.0, you could change the context path by specifying the spring property:

```yaml
server:
  servlet:
    context-path: /fake-smtp
```

This would have the effect of reaching the frontend server underneath `http://localhost:8080/fake-smtp`

With version 2.0.0 the frontend will not load anymore. The scripts seem to always be loaded using an absolute path:

E.g.:

`http://localhost:8080/static/js/main.ff156b3d.js` is trying to be loaded, but
`http://localhost:8080/fake-smtp/static/js/main.ff156b3d.js` would be the desired outcome

I now setting the context path is not a documented feature, but one that we rely one. Would be nice to support this somehow

Sample docker-compose:

```yaml
version: "3"
services:
  fake-smtp:
    image: gessnerfl/fake-smtp-server:2.0.0
    ports:
      - "8080:1080"
    environment:
        SERVER_SERVLET_CONTEXT-PATH: /fake-smtp
        SERVER_PORT: 1080
        FAKESMTP_PORT: 1025
```

**Comment by gessnerfl** [comment]
@gregor-rieble this issue should be fixed with version 2.0.1.
Can you please cross check.

**Comment by gregor-rieble** [comment]
Thank you for the changes, unfortunately, it did not fix the issue for me :(
I have created a PR: https://github.com/gessnerfl/fake-smtp-server/pull/161
Don't know if this is the most elegant solution, though

**Comment by gessnerfl** [comment]
@gregor-rieble  I think your solution is more elegant compared to mine. I merged it and tested it on my machine as well.
The fix is included in release 2.0.2

**Comment by gessnerfl** [comment]
closing the ticket after one month of inactivity and missing response
